GET http://localhost:8080/hello
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

####

GET http://localhost:8080/hello
Authorization: Basic YWRtaW46c2FkZmxrc2FqZmRs

####

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}